
<?php echo $this->getContent(); ?>

<?php echo $category['categoryId']>0 ? $this->tag->form("category/update") : $this->tag->form("category/create"); ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("category", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit category</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="cat_name">Cat Of Name</label>
        </td>
        <td align="left">
        <input type="text" name="categoryName" value="<?php echo $category['categoryName'];?>" />
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="parent_id">Parent</label>
        </td>
        <td align="left">
        
        	<?php foreach ($categoryList as $item){
        	?>
        	<option value="<?php echo $item['categoryId'];?>" <?php echo $item['categoryId'] == $category['parentId'] ? "selected" : '' ?>><?php echo $item['layer'].$item['categoryName'];?></option>
        	<?php } 
        	?>
        </select>
     
        </td>
    </tr>

    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
        <textarea name="description" id="" cols="30" rows="10"><?php echo $category['description'];?></textarea>
        </td>
    </tr>

    <tr>
        <td><input type="hidden" name="categoryId" value="<?php echo $category['categoryId'];?>"/></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
