
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("category/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("category", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit category</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="parent_id">Parent</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("parent_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cat_name">Cat Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("cat_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="post_count">Post Of Count</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("post_count", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
