
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("category/new", "Create category")) ?>
</div>

<?php echo $this->tag->form(array("category/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search category</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="caterogry_id">Caterogry</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("caterogry_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="parent_id">Parent</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("parent_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cat_name">Cat Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("cat_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="post_count">Post Of Count</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("post_count", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
