<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("category/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("category/edit", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Caterogry</th>
            <th>Cat Of Name</th>
            <th>Description</th>
            <th>Post Of Count</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($categoryList as $category) { ?>
        <tr>
            <td><?php echo $category['categoryId']; ?></td>
            <td><?php echo $category['layer']. $category['categoryName']; ?></td>
            <td><?php echo $category['description']; ?></td>
            <td><?php echo $category['postCount'] ?></td>
            <td><?php echo $this->tag->linkTo(array("category/edit/" . $category['categoryId'], "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("category/delete/" . $category['categoryId'], "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
