
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("tag/new", "Create tag")) ?>
</div>

<?php echo $this->tag->form(array("tag/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search tag</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="tag_id">Tag</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("tag_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="tag_name">Tag Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("tag_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="post_count">Post Of Count</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("post_count", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
