<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("tag/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("tag/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Tag</th>
            <th>Tag Of Name</th>
            <th>Post Of Count</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $tag) { ?>
        <tr>
            <td><?php echo $tag->tag_id ?></td>
            <td><?php echo $tag->tag_name ?></td>
            <td><?php echo $tag->post_count ?></td>
            <td><?php echo $this->tag->linkTo(array("tag/edit/" . $tag->tag_id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("tag/delete/" . $tag->tag_id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("tag/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("tag/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("tag/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("tag/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
