<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("blog/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("blog/edit", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Post</th>
            <th>Title</th>
            <th>Author</th>
            <th>Content</th>
            <th>Status</th>
            <th>Crate Of Time</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $blog) { ?>
        <tr>
            <td><?php echo $blog->postId ?></td>
            <td><?php echo $blog->title ?></td>
            <td><?php echo $blog->authorId ?></td>
            <td><?php echo $blog->content ?></td>
            <td><?php echo $blog->status ?></td>
            <td><?php echo $blog->createTime ?></td>
            <td><?php echo $this->tag->linkTo(array("blog/edit/" . $blog->postId, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("blog/delete/" . $blog->postId, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("blog/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("blog/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("blog/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("blog/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
